version: '3'
services:
  babbage-web:
    image: babbage-web:latest
    ports:
     - "8880:8880"
    network_mode: bridge
  reader-web:
    image: reader-web:latest
    network_mode: bridge
    volumes:
     - ${WEB_CONTENT}:/content:ro
    ports:
     - "8882:8882"
